"""dashboard/pages/4_Packet_Monitor.py — Live table of every packet generated
this session, sourced from the Dispatcher via CommunicationResult objects."""

import os
import sys

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_DASHBOARD_DIR = os.path.abspath(os.path.join(_THIS_DIR, ".."))
if _DASHBOARD_DIR not in sys.path:
    sys.path.insert(0, _DASHBOARD_DIR)

import streamlit as st

import components
import utils

components.configure_page("Packet Monitor", icon="📦")
ctx = utils.ensure_backend()
components.render_sidebar_status(ctx)

components.render_header("Packet Monitor", "All packets generated by the PacketGenerator and tracked by the Dispatcher")

dispatcher_stats = ctx.pipeline.dispatcher.get_statistics()
components.metric_row([
    ("Pending", dispatcher_stats["pending_count"]),
    ("In Transmission", dispatcher_stats["transmission_count"]),
    ("Delivered", dispatcher_stats["delivered_count"]),
    ("Failed", dispatcher_stats["failed_count"]),
    ("Packet Delivery Ratio", utils.fmt_pct(dispatcher_stats["packet_delivery_ratio"])),
])

st.divider()

packets = st.session_state.get("packet_log", [])

f1, f2, f3 = st.columns(3)
with f1:
    status_filter = st.multiselect(
        "Filter by Status",
        options=sorted({p.status.name for p in packets}) if packets else [],
    )
with f2:
    priority_filter = st.multiselect(
        "Filter by Priority",
        options=sorted({p.priority.name for p in packets}) if packets else [],
    )
with f3:
    search_term = st.text_input("Search Packet ID / Message ID")

filtered = packets
if status_filter:
    filtered = [p for p in filtered if p.status.name in status_filter]
if priority_filter:
    filtered = [p for p in filtered if p.priority.name in priority_filter]
if search_term:
    term = search_term.strip().lower()
    filtered = [p for p in filtered if term in p.packet_id.lower() or term in p.message_id.lower()]

st.caption(f"Showing {len(filtered)} of {len(packets)} tracked packet(s).")
st.dataframe(components.packets_dataframe(filtered), use_container_width=True, hide_index=True)

st.divider()
components.auto_refresh_control("packet_monitor")